version: '2'

services:
  bitcoin:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-mainnet

  bitcoin-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-testnet

  addrindexrs:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-base-mainnet

  addrindexrs-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: addrindexrs-base-testnet

  counterparty:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-mainnet
    links:
      - bitcoin
      - addrindexrs

  counterparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-testnet
    links:
      - bitcoin-testnet
      - addrindexrs-testnet

  mongodb:
    extends:
      file: docker-compose.tmpl.yml
      service: mongodb-base

  redis:
    extends:
      file: docker-compose.tmpl.yml
      service: redis-base

  armory-utxsvr:
    extends:
      file: docker-compose.tmpl.yml
      service: armory-utxsvr-base-mainnet
    links:
      - bitcoin

  armory-utxsvr-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: armory-utxsvr-base-testnet
    links:
      - bitcoin-testnet

  xcp-proxy:
    extends:
      file: docker-compose.tmpl.yml
      service: xcp-proxy-base-mainnet
    links:
      - redis
      - bitcoin
      - counterparty

  xcp-proxy-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: xcp-proxy-base-testnet
    links:
      - redis
      - bitcoin-testnet
      - counterparty-testnet

  http-addrindexrs:
    extends:
      file: docker-compose.tmpl.yml
      service: http-addrindexrs-base-mainnet
    links:
      - bitcoin
      - addrindexrs
      
  http-addrindexrs-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: http-addrindexrs-base-testnet
    links:
      - bitcoin-testnet
      - addrindexrs-testnet    

volumes:
  bitcoin-data:
  addrindexrs-data:
  counterparty-data:
  mongodb-data:
  armory-data:
